import { Inter } from "next/font/google";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slidbar from "./component/slidebar";
import Headerpage from "./component/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background overflow-hidden`}>
        <div className="fixed z-[2000] md:absolute left-0 md:left-10 -bottom-7 md:top-1/2 -translate-y-1/2 w-full md:w-fit">
          <Slidbar />
        </div>
        <div>
          <Headerpage />
          {children}
        </div>
      </body>
    </html>
  );
}
